### ISSUE TITLE
Tracking tools

### ISSUE THREAD

**Issue by josemuck** [josemuck/github-slideshow#4]
Tracking tools are required to measure the performance and identify options for optimization. 
The recommended tools are mapped in https://miro.com/app/board/uXjVNvXZZA8=/

**Problem**
Tools need to be bought and approved by IT. 
Tools need to be paid. Who pays for them needs to be decided. 

**ToDo's**

- [ ] Align with other squads about what tools are being required to see if there are any synergies, specially with Germany.
- [ ] A conversation with Nico and Mike in regards the needs for tooling and the process for getting them.
- [ ] Define further next steps.
